image: node:10

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  only: 
    - develop
  script: 
    - npm install --unsafe-perm node-sass
    - npm install
    - npm run build

deploy:
  stage: deploy
  only:
    - staging
  
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$STAGE_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - echo "Deploy project on server"
    - echo "$STAGE_DEPLOY_SERVER"
    - echo ubuntu@"$STAGE_DEPLOY_SERVER"
    - echo "$STAGE_SSH_PRIVATE_KEY"
    - bash .gitlab-stage-deploy.sh
    # - ssh -tt -i "~/.ssh/id_rsa" ubuntu@"$STAGE_DEPLOY_SERVER"