image: node:10

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  only: 
    - develop
  script: 
    - npm install --unsafe-perm node-sass
    - npm install
    - npm run build

deploy:
  stage: deploy
  only:
    - staging
  
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$STAGE_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa

  script:
    - echo "Deploy project on server"
    - echo "$STAGE_DEPLOY_SERVER"
    - echo ubuntu@"$STAGE_DEPLOY_SERVER"
    - ssh -tt -i "~/.ssh/id_rsa" ubuntu@"$STAGE_DEPLOY_SERVER"
    - cd /var/www
    - sudo touch test