image: node:10

before_script:
  - mkdir -p ~/.ssh    
  - echo "$AWS_SECRET_ACCESS_KEY_STAGING" >> ~/.ssh/front_key.pem
  - chmod 400 ~/.ssh/front_key.pem

cache:
  paths:
    - node_modules/

stages:
  - build

build:
  stage: build
  only: 
    - develop
  script: 
    - npm install --unsafe-perm node-sass
    - npm install
    - npm run build

deploy:
  stage: deploy
  only:
    - staging
  
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$STAGE_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

  script:
    - echo "Deploy project on server"
    - echo "$STAGE_DEPLOY_SERVER"
    - ssh -i "~/.ssh/id_rsa" ubuntu@$STAGE_DEPLOY_SERVER
    - cd /var/www
    - sudo touch test