image: node:10

before_script:
  - mkdir -p ~/.ssh    
  - echo "$AWS_SECRET_ACCESS_KEY_STAGING" >> ~/.ssh/front_key.pem
  - chmod 400 ~/.ssh/front_key.pem

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  only: 
    - develop
  script: 
    - npm install --unsafe-perm node-sass
    - npm install
    - npm run build

deploy_code:
  stage: deploy
  only:
    - staging
  script:
    - ssh -tt -i "~/.ssh/front_key.pem" ubuntu@ec2-3-14-13-164.us-east-2.compute.amazonaws.com
    - cd /var/www
    - sudo touch ci_here