image: node:10

cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  - deploy
  - deploy_prod

test:
  stage: test
  script:
    - echo "Testing!"

build:
  stage: build
  script: 
    - npm install --unsafe-perm node-sass
    - npm install
    - npm run build

deploy:
  stage: deploy
  only:
    - staging
  
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$STAGE_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - echo "Deploy project on server"
    - echo ubuntu@"$STAGE_DEPLOY_SERVER"
    - bash .gitlab-stage-deploy.sh

deploy_prod:
  stage: deploy_prod
  only:
    - master
  
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$PROD_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - echo "Deploy project on server"
    - echo ubuntu@"$PROD_DEPLOY_SERVER"
    - bash .gitlab-stage-deploy.sh