image: node:10

before_script:
  - mkdir -p ~/.ssh    
  - echo "$AWS_SECRET_ACCESS_KEY_STAGING" >> ~/.ssh/front_key.pem
  - chmod 400 ~/.ssh/front_key.pem

cache:
  paths:
    - node_modules/

stages:
  - build

build:
  stage: build
  only: 
    - develop
  script: 
    - npm install --unsafe-perm node-sass
    - npm install
    - npm run build