export default {
  notFound: { name: '404', path: '*', exactPath: '*' },
  home: { name: 'home', path: '/', exactPath: '/' },
  register: { name: 'register', path: '/register', exactPath: '/register' },
  registerAffiliate: {
    name: 'register-affiliate',
    path: '/register/:affiliate',
    exactPath: (affiliate: string) => `/register/${affiliate}`,
  },
  main: { name: 'main', path: '/main', exactPath: '/main' },
  deposit: { name: 'deposit', path: '/deposit', exactPath: '/deposit' },
  withdraw: { name: 'withdraw', path: '/withdraw', exactPath: '/withdraw' },
  transaction: { name: 'transaction', path: '/transaction', exactPath: '/transaction' },
  transactionDetail: { name: 'transaction-detail', path: '/transaction/detail', exactPath: '/transaction/detail' },
  lotto: { name: 'lotto', path: '/lotto', exactPath: '/lotto' },
  lottoChrildren: {
    name: 'lotto-chrildren', path: '/lotto/:type', exactPath: (type: string) => `/lotto/${type}`,
  },
  lottoMaking: {
    name: 'lotto-making', path: '/lotto/making/:type', exactPath: (type: string) => `/lotto/making/${type}`,
  },
  lottoCheckout: { name: 'lotto-checkout', path: '/checkout/lotto', exactPath: '/checkout/lotto' },
  lottoFavorite: { name: 'lottoFavorite', path: '/lotto-favorite', exactPath: '/lotto-favorite' },
  lottoFavoriteManagement: { name: 'lotto-favorite-management', path: '/lotto-favorite/management', exactPath: '/lotto-favorite/management' },
  lottoFavoriteAdd: { name: 'lotto-favorite-management-add', path: '/lotto-favorite/management/add', exactPath: '/lotto-favorite/management/add' },
  lottoFavoriteEdit: { name: 'lotto-favorite-management-edit', path: '/lotto-favorite/management/edit', exactPath: '/lotto-favorite/management/edit' },
  creditInfo: { name: 'credit-info', path: '/credit-info', exactPath: '/credit-info' },
  affiliate: { name: 'affiliate', path: '/affiliate', exactPath: '/affiliate' },
  contactus: { name: 'contact-us', path: '/contactus', exactPath: '/contactus' },
  newsroom: { name: 'newsroom', path: '/newsroom', exactPath: '/newsroom' },
  forgotPassword: { name: 'forgot-password', path: '/forgot-password', exactPath: '/forgot-password' },
  qa: { name: 'qa', path: '/qa', exactPath: '/qa' },
  qaType: { name: 'qa-type', path: '/qa/:type', exactPath: (type: TQAType) => `/qa/${type}` },
  casino: { name: 'casino', path: '/casino', exactPath: '/casino' },
  bacara: { name: 'bacara', path: '/casino/bacara', exactPath: '/casino/bacara' },
  slots: { name: 'slots', path: '/casino/slots', exactPath: '/casino/slots' },
  games: { name: 'games', path: '/games', exactPath: '/games' },
}